version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "/"
    labels:
      - "Dependencies"
    reviewers:
      - "novustheory"
    target-branch: "development"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "⬆️ "
    groups:
      # Forge uses the same version for every individual package. This keeps the pull request for forge grouped together
      electron-forge-dependencies:
        patterns:
          - "@electron-forge/*"
    ignore:
      - dependency-name: "electron"
        update-types: ["version-update:semver-patch"]
