---
name: Application Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        arch: [ 'x64', 'arm64' ]
        exclude:
          # Mitigation for Electron Forge naming conflict. See #1183.
          - os: 'windows-latest'
            arch: 'arm64'
        
      fail-fast: true # Explicitly failing fast because this is a publish. We want to bail the entire release if something went wrong with another build

    runs-on: ${{ matrix.os }}

    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - name: Corepack Enable Yarn
        run: corepack enable yarn

      - name: Setup Node (v20)
        uses: actions/setup-node@v4
        with:
          # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
          cache: 'yarn'
          node-version: "20.9.0"

      - name: Install dependencies
        run: yarn --immutable

      - name: Publish Dry (${{ matrix.arch }})
        env:
          YTMD_UPDATE_FEED_OWNER: ${{ vars.YTMD_UPDATE_FEED_OWNER }}
          YTMD_UPDATE_FEED_REPOSITORY: ${{ vars.YTMD_UPDATE_FEED_REPOSITORY }}
        run: yarn publish:dry --arch ${{ matrix.arch }}

      - name: Publish From Dry (${{ matrix.arch }})
        run: yarn publish:fromdry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YTMD_UPDATE_FEED_OWNER: ${{ vars.YTMD_UPDATE_FEED_OWNER }}
          YTMD_UPDATE_FEED_REPOSITORY: ${{ vars.YTMD_UPDATE_FEED_REPOSITORY }}
